// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Shaver")>]
[<assembly: AssemblyProductAttribute("Shaver")>]
[<assembly: AssemblyDescriptionAttribute("Lightweight F# library for Suave.io web server using Razor engine adding some extra features like template composing, custom return codes or localization resources support.")>]
[<assembly: AssemblyVersionAttribute("1.3.1")>]
[<assembly: AssemblyFileVersionAttribute("1.3.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Shaver"
    let [<Literal>] AssemblyProduct = "Shaver"
    let [<Literal>] AssemblyDescription = "Lightweight F# library for Suave.io web server using Razor engine adding some extra features like template composing, custom return codes or localization resources support."
    let [<Literal>] AssemblyVersion = "1.3.1"
    let [<Literal>] AssemblyFileVersion = "1.3.1"
